### ISSUE TITLE
[BUG] House number missing when new address created in checkout

### ISSUE THREAD

**Issue by JoostWan** [tig-nl/postnl-magento2#172]
**To Reproduce**

1. Create account
2. Create address inside the account (Or use account that's already contains a address).
3. Go to checkout
4. Click on New Address
5. Enter a address with housenumber and addition
6. Click on ship here. 
7. Adres is loaded and selected in checkout but doesn't show housenumber and addition. 

**Expected result**
Shows the housenumber and addition of the address. 

**Actual result**
 Adres is loaded and selected in checkout but doesn't show housenumber and addition. 

![Screenshot 2020-05-12 at 09 33 09](https://user-images.githubusercontent.com/5435412/81652220-ae7ea600-9433-11ea-9b1b-b692e3e12084.png)
![Screenshot 2020-05-12 at 09 32 38](https://user-images.githubusercontent.com/5435412/81652224-b0486980-9433-11ea-8944-89e627038ce7.png)

**Screenshots**

** Please complete the following information**
- Magento version: 2.3.5
- PHP version: 7.2
- TIG PostNL version: 1.9.1.1

**Comment by tig-jaspersmits** [comment]
Hi @JoostWan ,

Thanks for letting us know. I'll try to reproduce it and get back to you after I've tested.

Kind regards,
Jasper
TIG

**Comment by tig-jaspersmits** [comment]
Hi @JoostWan ,

I've been able to reproduce this and created a backlog ticket for it. We will work on a solution and will release it in a new version of the extension as soon as it's possible.

Thanks again for letting us know.

Kind regards,
Jasper
TIG

**Comment by tig-jaspersmits** [comment]
This should be fixed in the new release.
I will close the ticket.

Kind regards,
Jasper
TIG

**Comment by JoostWan** [comment]
@tig-jaspersmits It's still not working over here. We tested it on latest version. It's working when postcode check is disabled but when you enable it and enter a house number  or/and addition it's not showing. 

<img width="1223" alt="Screenshot 2020-11-28 at 17 54 54" src="https://user-images.githubusercontent.com/5435412/100521295-06e47d80-31a3-11eb-9281-f13cdde76e82.png">
<img width="1253" alt="Screenshot 2020-11-28 at 17 56 14" src="https://user-images.githubusercontent.com/5435412/100521297-0815aa80-31a3-11eb-8f91-1883c713868c.png">

**Comment by tig-jaspersmits** [comment]
Hi @JoostWan ,

Thanks for your message. Are you using version 1.9.5?

Kind regards,
Jasper
TIG

**Comment by JoostWan** [comment]
Yes. 

```
"name": "tig/postnl-magento2",
    "description": "TIG Magento 2 PostNL extension",
    "require": {
        "php": "~7.0|~7.1|~7.2|~7.3|~7.4",
        "ext-soap": "*",
        "magento/framework": "~102.0|~103.0",
        "setasign/fpdf": "^1.8.2",
        "setasign/fpdi": "^2.3.2",
        "laminas/laminas-barcode" : "~2.5|~2.8"
    },
    "type": "magento2-module",
    "license": "CC-BY-NC-ND-3.0",
    "version": "1.9.5",
```

**Comment by tig-jaspersmits** [comment]
Hi @JoostWan ,

That's strange, but you are right. I will discuss this again with the team.
I'll inform you when I have more information.

Kind regards,
Jasper
TIG

**Comment by tig-jeffreybranderhorst** [comment]
Hi @JoostWan ,

It has been a while since an update I see, but this should be fixed in the newest version of our PostNL extension.  If you have installed the newest extension and still are having problems with this don't hesitate to contact us at support@tig.nl!

Have a great day,
Jeffrey
